feat: 구매자 회원가입 API 추가
f-lab-edu/send-box pull request #12
Opened 2024-10-22 15:54 UTC by kamser0415

## #️⃣연관된 이슈
> ex) #이슈번호, #이슈번호

## 📝작업 내용
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)

## :black_nib: 코드 변경 이유
- 변경 사항이 필요한 이유와 프로젝트에 미치는 영향을 설명해주세요.

## 💬리뷰 요구사항(선택)
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?

2024-10-23 13:07 UTC, f-lab-jd commented on src/main/java/shop/sendbox/sendbox/buyer/Buyer.java
> +	private String deleteYN;
yn 값만 저장하기 위한 용도로 적당한 타입은 뭐가 있을까요~?

2024-10-23 13:07 UTC, f-lab-jd commented on src/main/java/shop/sendbox/sendbox/buyer/ApiResponse.java
> +public class ApiResponse<T> {
응답을 위한 별도 클래스를 사용하는 이유가 무엇인가요?

2024-10-23 13:07 UTC, f-lab-jd commented on src/main/java/shop/sendbox/sendbox/buyer/Buyer.java
> +	@Builder
builder 어노테이션 위치

2024-10-23 13:07 UTC, f-lab-jd commented on src/main/java/shop/sendbox/sendbox/buyer/BuyerService.java
> +	public BuyerResponse signUp(final BuyerRequest buyerRequest, final LocalDateTime createdAt) {
Transaction

2024-10-24 11:54 UTC, kamser0415 commented on src/main/java/shop/sendbox/sendbox/buyer/Buyer.java
> +	private String deleteYN;
Char 자료형을 사용하여 선언하는 방법과 Enum을 사용하는 방법이 있습니다.
Char 자료형은 단순하게 설정할 수 있다는 장점이 있고, Enum에 비해 오버헤드가 없습니다.
다만 타입 안정성이 떨어집니다. 다른 값들이 들어오는 경우 체크 로직을 별도로 구현해야합니다.

하지만 Enum은 Char 자료형보다 오버헤드가 발생할 수 있고 별도의 클래스로 분리해야하는 일이 생깁니다.
다만, Enum은 타입 안정성과 재활용이 가능하다는 장점이 있습니다.

2024-10-24 12:08 UTC, kamser0415 commented on src/main/java/shop/sendbox/sendbox/buyer/ApiResponse.java
> +public class ApiResponse<T> {
HTTP 에서 예외 객체는 표준이 있지만 성공 응답에는 표준이 없습니다.
클라이언트 측과 상의후에 결정하는 것이 맞지만
저는 예외 응답과 성공 응답을 동일한 양식을 가져가면 테스트나 API를 만들 때에 일관된 처리를 할 수 있다는 장점이 있는 거같아서 별도의 클래스를 만들었습니다.

2024-10-24 12:11 UTC, kamser0415 commented on src/main/java/shop/sendbox/sendbox/buyer/Buyer.java
> +	@Builder
Builder는 특정 필드를 제외하는 어노테이션이 없다고합니다.
제가 ToString 어노테이션이랑 헷갈린거 같습니다.

다시 생각해보니 빌더 패턴은 private으로 숨기고 내부에서만 사용할 목적이기 때문에 클래스 위에 있어도 상관없는 거같습니다.

2024-10-24 12:11 UTC, kamser0415 commented on src/main/java/shop/sendbox/sendbox/buyer/BuyerService.java
> +	public BuyerResponse signUp(final BuyerRequest buyerRequest, final LocalDateTime createdAt) {
명시적으로 트랜잭션으로 추가하겠습니다.

2024-10-24 14:47 UTC, f-lab-jd commented on build.gradle
> +    implementation 'com.google.guava:guava:33.3.1-jre'
guava 의존을 추가한 이유가 있으신가요~?

2024-10-24 14:47 UTC, f-lab-jd commented on src/main/java/shop/sendbox/sendbox/buyer/Buyer.java
> +// 엔티티를 생성하기 위해서 기본 생성자가 필요하지만 최소한으로 제한하기 위해 @NoArgsConstructor(access = AccessLevel.PROTECTED)를 사용했습니다.
사용 목적이 아니라, 어노테이션이 의미하는 내용 혹은 동작방식을 적어주시면 더 좋을 것 같습니다.

2024-10-24 14:47 UTC, f-lab-jd commented on src/main/java/shop/sendbox/sendbox/buyer/Buyer.java
> +	private String salt;
`salt` 는 왜 필요한가요~?

2024-10-24 14:47 UTC, f-lab-jd commented on src/main/java/shop/sendbox/sendbox/buyer/BuyerResponse.java
> +@Builder
Builder 의 accessLevel 도 설정하면 좋을 것 같습니다.

2024-10-25 14:14 UTC, kamser0415 commented on build.gradle
> +    implementation 'com.google.guava:guava:33.3.1-jre'
자바에서 기본적으로 제공하는 MessageDigest은 쓰레드에 안전하지 않다고 합니다.
출처: https://www.baeldung.com/sha-256-hashing-java
매번 새 인스턴스를 호출하는 방식으로 사용하라고 합니다.

그래서 저는 구아바는 검색해보니 쓰레드에 안전하다고 해서 의존성을 추가 했습니다.
멘토님께서 질문을 주신 이후에 구아바가 왜 쓰레드에 안전할까 검색해보니
불변객체로 내부에서 해싱을 할 때마다 새 인스턴스를 만들어서 처리를 합니다.

2024-10-25 14:15 UTC, kamser0415 commented on src/main/java/shop/sendbox/sendbox/buyer/Buyer.java
> +// 엔티티를 생성하기 위해서 기본 생성자가 필요하지만 최소한으로 제한하기 위해 @NoArgsConstructor(access = AccessLevel.PROTECTED)를 사용했습니다.
이해했습니다. 수정하겠습니다 !! :)

2024-10-25 14:18 UTC, kamser0415 commented on src/main/java/shop/sendbox/sendbox/buyer/Buyer.java
> +	private String salt;
해싱은 원 재료(패스워드)가 동일할 경우 항상 동일한 해싱결과를 반환합니다.
그래서 해싱은 무결성이 필요한 곳에서 사용하게 된다고 학습했습니다.

그러다보니 미리 해싱된 결과를 저장해서 해킹을 시도하는 레인보우 테이블을 방지하고자 salt를 추가했습니다.

ERD에는 추가되어있지 않지만, salt를 적용하고 싶어서 추가했습니다.

2024-10-25 14:18 UTC, kamser0415 commented on src/main/java/shop/sendbox/sendbox/buyer/BuyerResponse.java
> +@Builder
네 알겠습니다 !

2024-10-27 14:38 UTC, f-lab-jd commented on src/main/java/shop/sendbox/sendbox/buyer/BuyerController.java
> +// RequiredArgsConstructor는 생성자에 필요한 필수 파라미터가 포함된 생성자를 만들어줍니다.
multi line comments 의 경우 java 의 문법과 프로젝트의 일관성에 맞추어서 작성하시면 더 좋을 것 같습니다

(https://github.com/f-lab-edu/send-box/pull/12/files#diff-c5da6f50babf232f2aabceb685ac258ab17ee246ceadd10a718ec681e7aeded4R78)

2024-10-27 14:38 UTC, f-lab-jd commented on src/main/java/shop/sendbox/sendbox/buyer/BuyerController.java
> +	private final BuyerService buyerService;
빈 주입 방식으로 생성자 주입을 하신 이유가 무엇인가요?

2024-10-27 14:38 UTC, f-lab-jd commented on src/main/java/shop/sendbox/sendbox/buyer/BuyerController.java
> +	public ApiResponse<BuyerResponse> signUp(@RequestBody BuyerCreateRequest buyerCreateRequest) {
어노테이션 설명이 없습니다.

2024-10-27 14:38 UTC, f-lab-jd commented on src/main/java/shop/sendbox/sendbox/buyer/BuyerService.java
> +	@Transactional
어노테이션 설명이없습니다.

2024-10-27 14:38 UTC, f-lab-jd commented on src/main/java/shop/sendbox/sendbox/util/EncryptUtil.java
> +	static final int saltLength = 16;
네이버 핵데이 자바 컨벤션에 맞지 않은 상수표기법입니다.

2024-10-27 14:38 UTC, f-lab-jd commented on src/main/resources/application.yaml
> +---
profile 별로 파일을 분리하시는 것은 어떨까요?

2024-10-27 14:38 UTC, f-lab-jd commented on src/test/java/shop/sendbox/sendbox/buyer/ApiResponseTest.java
> +	@Test
어노테이션 설명이없습니다.

2024-10-27 14:38 UTC, f-lab-jd commented on src/test/java/shop/sendbox/sendbox/buyer/ApiResponseTest.java
> +		// Assertions.assertThat(apiResponse.getStatusCode()).isEqualTo(statusCode.value());
주석을 하신 이유가 무엇인가요? 
주석에는 주석 사유도 포함되어야합니다.

2024-10-28 10:29 UTC, kamser0415 commented on src/main/java/shop/sendbox/sendbox/buyer/BuyerController.java
> +// RequiredArgsConstructor는 생성자에 필요한 필수 파라미터가 포함된 생성자를 만들어줍니다.
네알겠습니다.

2024-10-28 13:05 UTC, kamser0415 commented on src/main/java/shop/sendbox/sendbox/buyer/BuyerController.java
> +	private final BuyerService buyerService;
생성자 주입을 사용한 이유는 테스트 코드 작성시 의존성 클래스를 변경하여 테스트를 할 수 있습니다.
또한 생성자 주입을 할 경우 의존성을 final 로 제한하여 빈이 생성된 이후 의존성을 변경할 수 없으므로
애플리케이션 서비스의 일관성을 보장할 수 있습니다

2024-10-28 13:05 UTC, kamser0415 commented on src/main/java/shop/sendbox/sendbox/buyer/BuyerController.java
> +	public ApiResponse<BuyerResponse> signUp(@RequestBody BuyerCreateRequest buyerCreateRequest) {
추가하도록 하겠습니다.

2024-10-28 13:05 UTC, kamser0415 commented on src/main/java/shop/sendbox/sendbox/buyer/BuyerService.java
> +	@Transactional
추가 하도록 하겠습니다.

2024-10-28 13:08 UTC, kamser0415 commented on src/main/java/shop/sendbox/sendbox/util/EncryptUtil.java
> +	static final int saltLength = 16;
처음에 작성할 때 빨간 줄이 떠서 변경햇었는데
지금은 또 오류가 없네요. . :(
수정하겠습니다.

2024-10-28 13:09 UTC, kamser0415 commented on src/main/resources/application.yaml
> +---
변경하도록 하겠습니다.

2024-10-28 13:18 UTC, kamser0415 commented on src/test/java/shop/sendbox/sendbox/buyer/ApiResponseTest.java
> +		// Assertions.assertThat(apiResponse.getStatusCode()).isEqualTo(statusCode.value());
주석을 잘못 했습니다.
최신 데이터에는 주석이 없습니다.
만약 주석을 사용한다면 사유를 포함하도록 하겠습니다.

2024-10-28 13:43 UTC, kamser0415 commented on src/test/java/shop/sendbox/sendbox/buyer/ApiResponseTest.java
> +	@Test
추가했습니다 !

2024-10-29 16:44 UTC, f-lab-jd commented on build.gradle
> +    implementation 'com.google.guava:guava:33.3.1-jre'
해당 객체가 쓰레드에 안전해야하는 이유가 있나요? 
그리고 현재 사용하는 부분이 없다면, 제거하는게 유지보수에 좋습니다.

2024-11-09 13:47 UTC, f-lab-jd reviewed
예전에 리뷰드렸던 내용 포함해서 다시 한번 확인 부탁드립니다.

2024-11-09 13:47 UTC, f-lab-jd commented on src/test/java/shop/sendbox/sendbox/buyer/ApiResponseTest.java
> +	@Test
추가한 내용이 보이지 않습니다. 테스트 어노테이션 관련해서 주석이없습니다.

2024-11-09 13:49 UTC, f-lab-jd requested changes
패키지 설계가 제대로 되어있는지 다시 한번 확인 부탁드립니다.
예를 들면, buyer 패키지 하위에 패키지를 나눌 필요는 없을까요?

2024-11-14 10:45 UTC, kamser0415 commented on build.gradle
> +    implementation 'com.google.guava:guava:33.3.1-jre'
네 알겠습니다 !!

2024-11-14 11:25 UTC, kamser0415 commented on src/test/java/shop/sendbox/sendbox/buyer/ApiResponseTest.java
> +	@Test
추가했습니다.

2024-11-17 17:29 UTC, f-lab-jd approved these changes
고생하셨습니다!

2024-11-24 06:47 UTC, merged