Feature/#4 hello
f-lab-edu/send-box pull request #5
Opened 2024-07-12 13:46 UTC by kamser0415

## #️⃣ 연관된 이슈
Closes #4

## 📝 작업 내용
- hello 기능 추가

## :black_nib: 코드 변경 이유
- 사용자에게 환영 메시지를 제공하기 위해 hello 기능을 추가하였습니다.

## 💬 리뷰 요구사항(선택)

2024-07-12 17:25 UTC, f-lab-jd requested changes

2024-07-12 17:25 UTC, f-lab-jd commented on HELP.md
> +# Getting Started
프로젝트와 협업을 위해 필요한 문서일까요?

2024-07-12 17:25 UTC, f-lab-jd commented on build/resolvedMainClassName
> +shop.sendbox.sendbox.SendboxApplication
build 디렉토리까지 remote 에 올라가는게 필요할까요? 
gitignore 정책을 전반적으로 검토부탁드립니다.

2024-07-13 01:19 UTC, kamser0415 commented on build/resolvedMainClassName
> +shop.sendbox.sendbox.SendboxApplication
맞습니다 !
수정하겠습니다

2024-07-13 01:25 UTC, kamser0415 commented on HELP.md
> +# Getting Started
필요한 문서는 아닙니다.

2024-07-13 16:24 UTC, f-lab-jd commented on build.gradle
> +	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
`spring-boot-starter-test` 와 별개로 해당 라이브러리를 추가하신 이유는 무엇인가요?

2024-07-14 04:06 UTC, kamser0415 commented on build.gradle
> +	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
implementation 'org.springframework.boot:spring-boot-starter-web'
이 라이브러리를 추가한 이유는 내장 톰캣 사용과 웹 어플리케이션을 개발할 때 필요한 여러 기능을 제공하기 때문입니다.

testImplementation 'org.springframework.boot:spring-boot-starter-test'
이 프레임워크는 Junit 테스트와 기타 테스트를 하기 위한 라이브러리로 앞으로 기능을 개발하기 위함입니다.

testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
Spring Boot 애플리케이션에서 JUnit 5 테스트를 실행하려면 JUnit 5 플랫폼 런처가 필요합니다.
이 런처를 추가하면 테스트 클래스를 찾고 실행할 수 있습니다

2024-07-16 17:13 UTC, f-lab-jd commented on build.gradle
> +	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
`starter-test` 에도 JUnit 5 가 포함되어있지 않나요~?
https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-test/3.3.1

2024-07-17 02:53 UTC, kamser0415 commented on build.gradle
> +	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
testRuntimeOnly 'org.junit.platform:junit-platform-launcher'가 추가된 이유입니다.

IDE 충돌 방지: IntelliJ IDEA와 같은 IDE에서 JUnit의 버전 충돌 문제를 방지하기 위함입니다. IDE에 번들된 JUnit 버전과 프로젝트에서 사용하는 JUnit 버전이 다를 때 발생할 수 있는 충돌을 예방합니다.

Gradle 버전 변경에 의한 호환성: Gradle 9에서 테스트 프레임워크 구현 의존성의 자동 로딩이 더 이상 지원되지 않기 때문에, 이를 명시적으로 선언하여 Gradle 9에서도 호환성을 유지합니다.

이 두 가지 이유로 testRuntimeOnly 'org.junit.platform:junit-platform-launcher' 의존성을 추가합니다.

## 참고
https://github.com/spring-io/initializr/issues/1476
https://junit.org/junit5/docs/current

2024-10-13 10:12 UTC, merged